version: '3'

services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
    command: npm run dev
    networks:
      - laravel-nuxt-network

networks:
  laravel-nuxt-network:
    external: true